
DROP TABLE IF EXISTS ids;

CREATE TABLE ids (
	id    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	code  VARCHAR(16) NOT NULL UNIQUE,
	value INT NOT NULL DEFAULT 1,
	created DATETIME NOT NULL,
	updated DATETIME NULL 
);

